### ISSUE TITLE
Crashes on any input

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [qader1/GPT-GUI#2]
Anytime I enter something, the program closes - not sure where to see logs to see what's causing the crash either

**Comment by qader1** [comment]
Are you using an OS other than windows? if so, this is expected. To fix this you need to remove all function calls from the library `pywinstyles` and remove the import. I'll push changes to check the OS before calling the functions. Their purpose to change the colors of the title bar which can only change on the OS level.

**Comment by Marshall-Hallenbeck** [comment]
I'm using win11

**Comment by qader1** [comment]
@Marshall-Hallenbeck I should have wrote a logger for the errors. Could you tell me how to reproduce it? did you make any changes before the crashes?

**Comment by Marshall-Hallenbeck** [comment]
I just installed it (defaulted to localappdata), added my api key, and type
in anything and it crashes/closes.

**Comment by qader1** [comment]
@Marshall-Hallenbeck It must be an uncaught error from the API, I'll write a logger, and add an exception for all api errors and display the error in a dialog. I'll push the changes and upload a new installer. If issues persisted, I'd appreciate feedback.
Thanks!

**Comment by Marshall-Hallenbeck** [comment]
Sounds good! I'll test it when you release it and let you know how it goes.

**Comment by qader1** [comment]
Hey @Marshall-Hallenbeck, I added a logger that creates log.txt file when exceptions are raised and handled API exceptions. Now you should see an error dialog in case of an API error. hopefully it's fixed. I already released it.

**Comment by Marshall-Hallenbeck** [comment]
@qader1 Ah I'm a big dumb and didn't even have access to GPT-4. I have access to it now, but here's the error that was being logged on the crash - Note I'm not sure why it says your personal project path on disk? It seems odd that would be hard-coded?

```ERROR:root:Traceback (most recent call last):

  File "C:\Users\Aboud\Projects\GPT-GUI\api.py", line 42, in run

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 601, in predict_messages

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 551, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 309, in generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 299, in generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 446, in _generate_with_cache

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 339, in _generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 278, in completion_with_retry

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 379, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 314, in iter

  File "C:\Users\Aboud\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result

  File "C:\Users\Aboud\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 382, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 276, in _completion_with_retry

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 298, in request

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\Aboud\Projects\GPT-GUI\api.py", line 45, in run

TypeError: catching classes that do not inherit from BaseException is not allowed
NoneType: None
```

Anyway, from this error you should be able to catch that error and make a pop up letting the user know  their account doesnt have access to GPT4 (which requires a minimum of $1 purchase).

**Comment by qader1** [comment]
@Marshall-Hallenbeck It's printing paths from my machine because the app was there frozen in bytecode. It's tracing the error successfully in the package because it's doing it relative to the path where it was frozen but it's printing the absolute paths. The only way is around it by to slice the paths' strings and it's just for aethetics; it has no effect. I'll do it in the next update now.

For the error, it's quite stupid. I wanted to use a generic exception defined in the OpenAI library but I used the entire error module instead of an exception, so i just need to change that in line 45 in api.py
update incoming. everything should work now.

btw, I hard coded gpt-4 as a model. If you want to change it to gpt-3.5, just open key.json as txt files and change the model there.

**Comment by qader1** [comment]
@Marshall-Hallenbeck Please try the new version. thanks!

**Comment by Marshall-Hallenbeck** [comment]
@qader1 I'm currently using 1.0.1 with an API key that has GPT4 access, so it hasn't crashed since I started using that. I'll download the new version in a bit.

Thanks for the quick fixes! I'll let you know if I run into any other issues. Closing this since my original issue has been resolved.
