### ISSUE TITLE
Crash when received tokens is too large

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [qader1/GPT-GUI#3]
Just randomly happened during usage:
```
ERROR:root:Traceback (most recent call last):

  File "C:\Users\Aboud\Projects\GPT-GUI\api.py", line 42, in run

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 601, in predict_messages

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 551, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 309, in generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 299, in generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\base.py", line 446, in _generate_with_cache

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 339, in _generate

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 278, in completion_with_retry

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 379, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 314, in iter

  File "C:\Users\Aboud\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result

  File "C:\Users\Aboud\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\tenacity\__init__.py", line 382, in __call__

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\langchain\chat_models\openai.py", line 276, in _completion_with_retry

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 298, in request

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response

  File "C:\Users\Aboud\Projects\GPT-GUI\venv\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line

openai.error.InvalidRequestError: This model's maximum context length is 8192 tokens. However, your messages resulted in 8211 tokens. Please reduce the length of the messages.
```

**Comment by Marshall-Hallenbeck** [comment]
It looks like my previous chat didn't save? I did update to 1.0.2 that you released, that might have deleted it? Or maybe it didn't save because of the crash.

**Comment by qader1** [comment]
@Marshall-Hallenbeck
1. The chat is probably not deleted only its reference in the csv file. When you reinstall, the new build replaces the old history.csv with an empty one. To get the chat again just add a row to csv with any title and date but use the name of the file as the id. The csv has 3 columns: `id`, `date`, and `title`. 
2. It shouldn't crash in 1.0.2, instead you will get an error dialog.
3. For each new message you send, the entire chat is sent to the API to get a "prediction". Context length is the length of fixed input vector to the model and there is no way around it, but to keep sending messages in the chat after exceeding the maximum context length, I could truncate the chat. It means old messages in chat will be displayed but the model will NOT read them. It shouldn't be complicated to implement. I'll do it in the next version.

**Comment by qader1** [comment]
@Marshall-Hallenbeck I solved the issue and released a new version. Thanks again for the bug reports.
